version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - uploaded_files:/code/uploads
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/code
    environment:
      - DEBUG=1

volumes:
  uploaded_files:
